"
A RSHorizontalDominanceTreeLayoutTest is a test class for testing the behavior of RSHorizontalDominanceTreeLayout
"
Class {
	#name : 'RSHorizontalDominanceTreeLayoutTest',
	#superclass : 'RSLayoutTest',
	#category : 'Roassal-Layouts-Tests',
	#package : 'Roassal-Layouts-Tests'
}

{ #category : 'utilities' }
RSHorizontalDominanceTreeLayoutTest >> apply [

	RSHorizontalDominanceTreeLayout new on: shapes
]
